### ISSUE TITLE
Missing readme.md

### ISSUE THREAD

**Issue by chris-gunawardena** [patelprashant/RxNdroid#1]
Hey champ,

Hope all is well, looks like an interesting mix of Rx and Android, wish there was a readme file to tell me more! Also I'm reading your cheat sheets, so keep updating them!

Chris =)

**Comment by patelprashant** [comment]
Hey Chris,
All good mate...how are you doing? Hope the lil one keeps you engaged. Yeah..I'll add readme doc, those are examples with RxJava and Android. Sure I'll try to keep the cheatsheet updated.
Regards,
-Prashant
